apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: false
  database:
    externalDb: false
  server:
    selfSignedCert: false
    gitSelfSignedCert: false
    tlsSupport: false
    devfileRegistryImage: 'celcin/devfile-2'
  storage:
    pvcStrategy: 'common'
    pvcClaimSize: '1Gi'